
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAllProducts", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.0.35:99/?wsdl")
public class GetAllProducts
    extends Service
{

    private final static URL GETALLPRODUCTS_WSDL_LOCATION;
    private final static WebServiceException GETALLPRODUCTS_EXCEPTION;
    private final static QName GETALLPRODUCTS_QNAME = new QName("http://tempuri.org/", "GetAllProducts");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.35:99/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETALLPRODUCTS_WSDL_LOCATION = url;
        GETALLPRODUCTS_EXCEPTION = e;
    }

    public GetAllProducts() {
        super(__getWsdlLocation(), GETALLPRODUCTS_QNAME);
    }

    public GetAllProducts(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETALLPRODUCTS_QNAME, features);
    }

    public GetAllProducts(URL wsdlLocation) {
        super(wsdlLocation, GETALLPRODUCTS_QNAME);
    }

    public GetAllProducts(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETALLPRODUCTS_QNAME, features);
    }

    public GetAllProducts(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAllProducts(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetAllProductsSoap
     */
    @WebEndpoint(name = "GetAllProductsSoap")
    public GetAllProductsSoap getGetAllProductsSoap() {
        return super.getPort(new QName("http://tempuri.org/", "GetAllProductsSoap"), GetAllProductsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAllProductsSoap
     */
    @WebEndpoint(name = "GetAllProductsSoap")
    public GetAllProductsSoap getGetAllProductsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "GetAllProductsSoap"), GetAllProductsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETALLPRODUCTS_EXCEPTION!= null) {
            throw GETALLPRODUCTS_EXCEPTION;
        }
        return GETALLPRODUCTS_WSDL_LOCATION;
    }

}
