
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 
     * @param customerId
     * @param serviceId
     * @param productId
     * @return
     *     returns int
     */
    @WebMethod(operationName = "product_service", action = "http://tempuri.org/product_service")
    @WebResult(name = "product_serviceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "product_service", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProductService")
    @ResponseWrapper(localName = "product_serviceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProductServiceResponse")
    public int productService(
        @WebParam(name = "service_id", targetNamespace = "http://tempuri.org/")
        String serviceId,
        @WebParam(name = "product_id", targetNamespace = "http://tempuri.org/")
        String productId,
        @WebParam(name = "customer_id", targetNamespace = "http://tempuri.org/")
        int customerId);

}
