
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Addition", action = "http://tempuri.org/Addition")
    @WebResult(name = "AdditionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Addition", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Addition")
    @ResponseWrapper(localName = "AdditionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AdditionResponse")
    public int addition(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        int a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        int b);

    /**
     * 
     * @param b
     * @param a
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Product", action = "http://tempuri.org/Product")
    @WebResult(name = "ProductResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Product", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Product")
    @ResponseWrapper(localName = "ProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProductResponse")
    public int product(
        @WebParam(name = "a", targetNamespace = "http://tempuri.org/")
        int a,
        @WebParam(name = "b", targetNamespace = "http://tempuri.org/")
        int b);

}
