/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2015-08-17 07:05:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showCustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction showCustomer(str)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar xmlhttp;\r\n");
      out.write("\t\tif(str.length==0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\tdocument.getElementById(\"txtHint\").innerHTML=\"\";//innerHTML is used to display the output in the place given by the id=t\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(window.XMLHttpRequest) //Non-IE. window object is used to find if the browser used is IE or not\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\txmlhttp=new XMLHttpRequest();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\txmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");//for IE\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\txmlhttp.onreadystatechange=function()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(xmlhttp.readyState==4 && xmlhttp.status==200)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"txtHint\").innerHTML=xmlhttp.responseText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\txmlhttp.open(\"GET\",\"getcustomer.jsp?nm=\"+str, true);\r\n");
      out.write("\t\txmlhttp.send();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("\t<select name=\"customers\" onchange=\"showCustomer(this.value)\">\r\n");
      out.write("\t<option value=\"\">Select a customer:</option>\r\n");
      out.write("\t<option value=\"SCOTT\"> SCOTT</option>\r\n");
      out.write("\t<option value=\"BLAKE\"> BLAKE</option>\r\n");
      out.write("\t<option value=\"MILLER\"> MILLER</option>\r\n");
      out.write("\t<option value=\"TURNER\"> TURNER</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<div id=\"txtHint\">Customer info will be listed here</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
