
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service1Soap {


    /**
     * 
     * @param cid
     * @return
     *     returns org.tempuri.ArrayOfClass2
     */
    @WebMethod(action = "http://tempuri.org/getservice")
    @WebResult(name = "getserviceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getservice", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Getservice")
    @ResponseWrapper(localName = "getserviceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetserviceResponse")
    public ArrayOfClass2 getservice(
        @WebParam(name = "cid", targetNamespace = "http://tempuri.org/")
        int cid);

}
